// Package bundle assembles a chart, its values, and its image tarballs into a
// single compressed archive ready for transfer to airgapped infrastructure.
package bundle

import (
	"archive/tar"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// ImageEntry pairs an image tarball on disk with the retagged reference it
// contains.
type ImageEntry struct {
	// TarPath is the path to the saved image archive.
	TarPath string
	// SourceRef is the original image reference.
	SourceRef string
	// DestRef is the retagged reference baked into the tarball.
	DestRef string
	// Digest is the resolved manifest digest of the pulled image
	// (e.g. "sha256:..."), empty when the registry did not report one.
	Digest string
}

// Spec describes the contents of a chart bundle.
type Spec struct {
	// ChartName is used to name the output archive.
	ChartName string
	// ChartVersion is included in the output archive name.
	ChartVersion string
	// ChartPath is the pulled chart .tgz to embed.
	ChartPath string
	// Values is the rendered default values.yaml content (optional).
	Values string
	// Images are the saved image tarballs to embed.
	Images []ImageEntry
	// OutputDir is where the bundle archive is written.
	OutputDir string
	// Compression selects the archive codec: "gzip" (default, .tar.gz) or
	// "zstd" (.tar.zst), which gives a smaller bundle for airgap transfer.
	Compression string
}

// Create writes the bundle archive and returns its path. The archive contains:
//
//	<chart>.tgz            the Helm chart
//	values.yaml            default chart values
//	images/<name>.tar      one tarball per image, retagged
//	images.txt             source -> dest reference manifest
//	sha256sums.txt         sha256 of every bundled file (sha256sum -c format)
//	load.sh                script to load and push every image
func Create(spec Spec) (path string, err error) {
	if err = os.MkdirAll(spec.OutputDir, 0o755); err != nil {
		return "", err
	}
	codec, ext, err := compressorFor(spec.Compression)
	if err != nil {
		return "", err
	}
	outName := fmt.Sprintf("%s-%s-bundle.tar.%s", spec.ChartName, spec.ChartVersion, ext)
	outPath := filepath.Join(spec.OutputDir, outName)
	out, err := os.Create(outPath)
	if err != nil {
		return "", err
	}
	defer func() {
		_ = out.Close()
		if err != nil {
			_ = os.Remove(outPath)
		}
	}()
	compWriter, err := codec(out)
	if err != nil {
		return "", err
	}
	defer func() {
		_ = compWriter.Close()
	}()
	tarWriter := tar.NewWriter(compWriter)
	defer func() {
		_ = tarWriter.Close()
	}()
	// checksums accumulates "<sha256>  <name>" lines (sha256sum -c format) for
	// every bundled file except load.sh and sha256sums.txt themselves.
	var checksums sums
	chartName := filepath.Base(spec.ChartPath)
	sum, err := writeFileFromDisk(tarWriter, spec.ChartPath, chartName)
	if err != nil {
		return "", err
	}
	checksums.add(sum, chartName)
	if spec.Values != "" {
		if sum, err = writeBytes(tarWriter, "values.yaml", []byte(spec.Values)); err != nil {
			return "", err
		}
		checksums.add(sum, "values.yaml")
	}
	var manifest strings.Builder
	for _, image := range spec.Images {
		name := "images/" + filepath.Base(image.TarPath)
		if sum, err = writeFileFromDisk(tarWriter, image.TarPath, name); err != nil {
			return "", err
		}
		checksums.add(sum, name)
		digest := image.Digest
		if digest == "" {
			digest = "-"
		}
		fmt.Fprintf(&manifest, "%s\t%s\t%s\t%s\n", image.SourceRef, image.DestRef, name, digest)
	}
	if sum, err = writeBytes(tarWriter, "images.txt", []byte(manifest.String())); err != nil {
		return "", err
	}
	checksums.add(sum, "images.txt")
	if _, err = writeBytes(tarWriter, "sha256sums.txt", []byte(checksums.String())); err != nil {
		return "", err
	}
	if _, err = writeBytesMode(tarWriter, "load.sh", []byte(buildLoadScript(spec.Images)), 0o755); err != nil {
		return "", err
	}
	return outPath, nil
}

// sums accumulates checksum lines in the "sha256sum -c" format:
// "<hex>  <relative-name>" (two spaces).
type sums struct {
	b strings.Builder
}

func (s *sums) add(hexSum, name string) {
	fmt.Fprintf(&s.b, "%s  %s\n", hexSum, name)
}

func (s *sums) String() string {
	return s.b.String()
}

// buildLoadScript returns a POSIX shell script that loads each bundled image
// tarball into a container engine and pushes it to its retagged reference. The
// engine defaults to docker and can be overridden with the ENGINE environment
// variable (e.g. ENGINE=podman ./load.sh). Set DRY_RUN=1 to print the load and
// push commands without executing them. The script is idempotent: an image
// already present locally is not re-loaded.
func buildLoadScript(images []ImageEntry) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Auto-generated by helmdownloader.\n")
	b.WriteString("# Loads every bundled image and pushes it to the target registry.\n")
	b.WriteString("# Requires docker, or set ENGINE=podman. Set DRY_RUN=1 to preview.\n")
	b.WriteString("set -eu\n\n")
	b.WriteString(`ENGINE="${ENGINE:-docker}"` + "\n")
	b.WriteString(`DRY_RUN="${DRY_RUN:-}"` + "\n")
	b.WriteString(`DIR="$(cd "$(dirname "$0")" && pwd)"` + "\n\n")
	// run executes a command, or just prints it under DRY_RUN.
	b.WriteString("run() {\n")
	b.WriteString(`  if [ -n "$DRY_RUN" ]; then echo "DRY_RUN: $*"; else "$@"; fi` + "\n")
	b.WriteString("}\n\n")
	// Verify file integrity before touching the registry. Skip cleanly when no
	// checksum tool is available rather than failing the whole load.
	b.WriteString("if [ -f \"$DIR/sha256sums.txt\" ]; then\n")
	b.WriteString("  if command -v sha256sum >/dev/null 2>&1; then\n")
	b.WriteString(`    echo ">> verifying checksums"` + "\n")
	b.WriteString(`    (cd "$DIR" && sha256sum -c sha256sums.txt)` + "\n")
	b.WriteString("  elif command -v shasum >/dev/null 2>&1; then\n")
	b.WriteString(`    echo ">> verifying checksums"` + "\n")
	b.WriteString(`    (cd "$DIR" && shasum -a 256 -c sha256sums.txt)` + "\n")
	b.WriteString("  else\n")
	b.WriteString(`    echo ">> no sha256sum/shasum found, skipping checksum verification" >&2` + "\n")
	b.WriteString("  fi\n")
	b.WriteString("fi\n\n")
	b.WriteString("load_and_push() {\n")
	b.WriteString(`  if [ -z "$DRY_RUN" ] && "$ENGINE" image inspect "$2" >/dev/null 2>&1; then` + "\n")
	b.WriteString(`    echo ">> $2 already present, skipping load"` + "\n")
	b.WriteString("  else\n")
	b.WriteString(`    echo ">> loading $1"` + "\n")
	b.WriteString(`    run "$ENGINE" load -i "$DIR/$1"` + "\n")
	b.WriteString("  fi\n")
	b.WriteString(`  echo ">> pushing $2"` + "\n")
	b.WriteString(`  run "$ENGINE" push "$2"` + "\n")
	b.WriteString("}\n\n")
	for _, image := range images {
		name := "images/" + filepath.Base(image.TarPath)
		if image.Digest != "" {
			fmt.Fprintf(&b, "# %s\n", image.Digest)
		}
		fmt.Fprintf(&b, "load_and_push %s %s\n", shellQuote(name), shellQuote(image.DestRef))
	}
	fmt.Fprintf(&b, "\necho \"done: loaded and pushed %d image(s)\"\n", len(images))
	return b.String()
}

// shellQuote wraps s in single quotes, escaping any embedded single quotes, so
// it is safe to interpolate into the generated shell script.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// writeFileFromDisk copies the file at srcPath into the archive under name and
// returns the hex-encoded sha256 of its contents.
func writeFileFromDisk(tarWriter *tar.Writer, srcPath, name string) (string, error) {
	file, err := os.Open(srcPath)
	if err != nil {
		return "", err
	}
	defer func() {
		_ = file.Close()
	}()
	info, err := file.Stat()
	if err != nil {
		return "", err
	}
	header := &tar.Header{
		Name:    name,
		Mode:    0o644,
		Size:    info.Size(),
		ModTime: info.ModTime(),
	}
	if err := tarWriter.WriteHeader(header); err != nil {
		return "", err
	}
	hasher := sha256.New()
	if _, err := io.Copy(io.MultiWriter(tarWriter, hasher), file); err != nil {
		return "", err
	}
	return hex.EncodeToString(hasher.Sum(nil)), nil
}

// writeBytes writes an in-memory file into the archive under name with the
// default 0o644 mode, returning the hex-encoded sha256 of data.
func writeBytes(tarWriter *tar.Writer, name string, data []byte) (string, error) {
	return writeBytesMode(tarWriter, name, data, 0o644)
}

// writeBytesMode writes an in-memory file into the archive under name with the
// given file mode, returning the hex-encoded sha256 of data.
func writeBytesMode(tarWriter *tar.Writer, name string, data []byte, mode int64) (string, error) {
	header := &tar.Header{
		Name: name,
		Mode: mode,
		Size: int64(len(data)),
	}
	if err := tarWriter.WriteHeader(header); err != nil {
		return "", err
	}
	if _, err := tarWriter.Write(data); err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}
